CREATE TABLE recette (
	nom VARCHAR(40) PRIMARY KEY,
    categorie VARCHAR(40),
    type VARCHAR(40),
    images TEXT,
    URL TEXT);
    
INSERT INTO recette (nom, categorie, type, images, URL) VALUES

("Soupe miso (Japonais)", "Asiatique", "Petit dej", "Images/Soupe miso.jpg", "https://www.marmiton.org/recettes/recette_miso-shiru-soupe-miso_23937.aspx"),
("Les tsukemono (Japonais)", "Asiatique", "Petit dej", "Images/Les tsukemono.jpg", "https://www.commeaujapon.fr/tsukemono-pickles-de-celeri/"),
("Poisson grillé (Japonais)", "Asiatique", "Petit dej", "Images/Poisson grillé.jpg", "https://pen-online.com/fr/food/maquereau-grille-facon-kabayaki-par-tim-anderson/"),
("Natto (Japonais)", "Asiatique", "Petit dej", "Images/Natto.jpg", "https://www.marmiton.org/recettes/recette_natto_391412.aspx"),


("Brioches fourrées à la viande (Chinois)", "Asiatique", "Petit dej", "Images/Brioches cuites à la vapeur et fourrées à la viande ou Bahn-Bao.jpg", "https://www.marmiton.org/recettes/recette_nikuman-delicieuse-brioches-au-porc-cuites-a-la-vapeur_224770.aspx"),
("Congee (Chinois)", "Asiatique", "Petit dej", "Images/Congee.jpg", "https://www.cuisineaz.com/recettes/congee-108362.aspx"),
("Nouilles sautées (Chinois)", "Asiatique", "Petit dej", "Images/Nouilles sautées.jpg", "https://www.marmiton.org/recettes/recette_simplissimes-nouilles-sautees-au-poulet_37164.aspx"),
("Crêpes aux œufs (Chinois)", "Asiatique", "Petit dej", "Images/Jian-Bing ou Crêpes aux oeufs.jpg", "https://www.marieclaire.fr/cuisine/jian-bing-crepes-chinoises-fourrees,1420923.asp"),
("Crêpes aux oignons verts (Chinois)", "Asiatique", "Petit dej", "Images/Crêpes aux oignons verts.jpg", "https://www.uneaiguilledanslpotage.com/2021/05/crepes-chinoises-aux-oignons-verts-cong-you-bing.html"),
("You Tiao (Chinois)", "Asiatique", "Petit dej", "Images/You Tiao.jpg", "https://www.cuisine-du-cambodge.com/recette/cha-kwai-you-tiao-banh-quay-beignets-frits/"),
("Gateau aux navets(Chinois)", "Asiatique", "Petit dej", "Images/LuoBuo Gao.jpg", "https://cookidoo.fr/recipes/recipe/fr-FR/r542622"),
("Jin Dui (Chinois)", "Asiatique", "Petit dej", "Images/Jin Dui.jpg", "https://food52.com/recipes/86388-jian-dui-recipe"),
("Pouding au tofu (Chinois)", "Asiatique", "Petit dej", "Images/Pouding au tofu.jpg", "https://www.196flavors.com/fr/douhua/"),
("Nouilles de blé (Chinois)", "Asiatique", "Petit dej", "Images/Nouilles de blé.jpg", "https://platetrecette.com/nouilles-de-ble-legumes-weight-watchers/"),
("Doushabao (Chinois)", "Asiatique", "Petit dej", "Images/Doushabao.jpg", "https://www.ptitchef.com/recettes/autre/deux-ans-apres-lecon-de-dou-sha-bao-fid-242484"),
("Mantou frit au lait (Chinois)", "Asiatique", "Petit dej", "Images/Mantou frit au lait.jpg", "https://www.196flavors.com/fr/chine-mantou/"),


("Peit déj traditionnel (Coréen)", "Asiatique", "Petit dej", "Images/tradi.png", "https://www.marmiton.org/recettes/recette_bibimbap-coreen_340709.aspx"),
("Oeufs et tofu (Coréen)", "Asiatique", "Petit dej", "Images/oeuf et tofu.jpg", "https://www.196flavors.com/fr/coree-du-sud-sundubu-jjigae/"),
("Oeufs toast sandwich (Coréen)", "Asiatique", "Petit dej", "Images/Oeufs toast sandwich Coreen.jpg", "https://sandwichs.net/recette-korean-street-toast/"),


("Uttapam (Indien)", "Asiatique", "Petit dej", "Images/uttapam.jpg", "https://www.vegrecipesofindia.com/onion-tomato-uthappam/"),
("Masala Dosa (Indien)", "Asiatique", "Petit dej", "Images/Masala Dosa.jpg", "https://www.marmiton.org/recettes/recette_dosa-crepe-d-inde-du-sud_57319.aspx"),
("Appam (Indien)", "Asiatique", "Petit dej", "Images/Appam.jpg", "https://www.finedininglovers.fr/recettes/petit-dejeuner/appam"),
("Pongal (Indien)", "Asiatique", "Petit dej", "Images/Pongal.jpg", "https://www.zeste.ca/recettes/recette-pongal"),
("Vada (Indien)", "Asiatique", "Petit dej", "Images/Vada.jpg", "https://www.196flavors.com/fr/sri-lanka-ulundu-vadai-medu-vada/"),
("Upma (Indien)", "Asiatique", "Petit dej", "Images/Upma.jpg", "https://www.sushin.fr/recette-upma-rava-upma"),
("Idiyappam (Indien)", "Asiatique", "Petit dej", "Images/Idiyappam.jpg", "https://www.196flavors.com/fr/sri-lanka-idiyappam/"),
("Puttu (Indien)", "Asiatique", "Petit dej", "Images/Puttu.jpg", "https://www.vegrecipesofindia.com/puttu-recipe/"),
("Poori masala (Indien)", "Asiatique", "Petit dej", "Images/Poori masala.jpg", "https://www.vegrecipesofindia.com/poori-masala-recipe-potato-masala/"),
("Roti (Indien)", "Asiatique", "Petit dej", "Images/Roti.jpg", "https://www.atelierdeschefs.fr/fr/recette/17314-chapati-indienne-pain-traditionnel-indien.php"),
("Bonda (Indien)", "Asiatique", "Petit dej", "Images/Bonda.jpg", "https://recipes.timesofindia.com/recipes/aloo-bonda/rs55051496.cms"),
("Paniyaram (Indien)", "Asiatique", "Petit dej", "Images/Paniyaram.jpg", "https://www.vegrecipesofindia.com/masala-paniyaram-recipe/"),


("Tartines","Francais", "Petit dej", "Images/tartine.jpg",""),
("Céréales", "Francais", "Petit dej", "Images/céréales.jpg", ""),
("Crêpe", "Francais", 'Petit déj', "Images/Crêpe.jpg", "https://www.marmiton.org/recettes/recette_pate-a-crepes-des-plus-raffinees_49665.aspx"),
("Pain au chocolat", "Francais", "Petit dej", "Images/Pain au chocolat.jpg", "https://www.marmiton.org/recettes/recette_pains-au-chocolat_29672.aspx"),
("Croissant", "Francais", "Petit dej", "Images/Croissant.jpg", "https://www.cuisineactuelle.fr/recettes/croissant-au-beurre-120996"),


("Veneziana", "Italien", "Petit dej", "Images/veneziana.jpg", "https://www.marmiton.org/recettes/recette_baccala-mantecato-alla-veneziana-brandade-venitienne_49769.aspx"),
("Ciabattas à la méditerranéenne", "Italien", "Petit dej", "Images/Ciabattas à la méditerranéenne.jpg", "https://madame.lefigaro.fr/recettes/ciabattas-mediterraneenne-290607-6474"),
("Panettone", "Italien", "Petit dej", "Images/panettone.jpg", "https://www.marmiton.org/recettes/recette_panettone-recette-secrete_222534.aspx"),
("Cappuccino", "Italien", "Petit dej", "Images/Cappuccino.jpg", "https://www.marmiton.org/recettes/recette_cappuccino_19650.aspx"),


("Oeufs au bacon (anglais)", "Anglophone", "Petit dej", "Images/Oeufs au bacon.jpg", "https://www.cuisineactuelle.fr/recettes/aeufs-sur-le-plat-au-bacon-238818"),
("English Breakfast", "Anglophone", "Petit dej", "Images/English Breakfast.jpg", "https://www.marmiton.org/recettes/recette_english-breakfast-petit-dejeuner-anglais_71425.aspx"),
("Pancakes (anglais)"),"Anglophone", "Petit dej", "Images/Pancakes.jpg", "https://www.marmiton.org/recettes/recette_pancakes_15299.aspx"),
("Potatos farls (anglais)"),"Anglophone", "Petit dej", "Images/Potatos farls.jpg", "https://www.cuisineaz.com/recettes/potatos-farls-galettes-irlandaises-a-la-pomme-de-terre-78489.aspx"),
("Scones à l'orange anglais"),"Anglophone", "Petit dej", "Images/Scones à l'orange anglais.jpg", "https://www.cuisineaz.com/recettes/scones-a-l-orange-anglais-90982.aspx"),
("Boudin noir (anglais)"),"Anglophone", "Petit dej", "Images/Boudin noir au four.jpg", "https://www.petitsplatsentreamis.com/boudin-noir-au-four/"),
("Muffins anglais"),"Anglophone", "Petit dej", "Images/Muffins anglais aux oeufs brouillés.jpg", "https://www.cuisineaz.com/recettes/muffins-anglais-aux-oeufs-brouilles-65568.aspx"),
("Marmelade d'orange (anglais)"),"Anglophone", "Petit dej", "Images/marmelade-d-orange.jpg", "https://www.mesinspirationsculinaires.com/article-marmelade-dorange.html"),
("English egg (anglais)"),"Anglophone", "Petit dej", "Images/English egg and bacon muffin.jpg", "https://www.cuisineaz.com/recettes/baked-beans-maison-65198.aspx"),
("Pommes de terres sautées (anglais)"),"Anglophone", "Petit dej", "Images/Pommes de terres sautées au jambon et oeufs pochés.jpg", "https://www.cuisineaz.com/recettes/pommes-de-terres-sautees-au-jambon-et-oeufs-poches-84292.aspx"),


("Œufs Bénédicte sur tartine (américain)", "Anglophone", "Petit dej", "Images/oeufs Bénédicte sur tartine.jpg", "https://www.marmiton.org/recettes/recette_oeufs-benedicte_36184.aspx"),
("Banana bread (américain)" , "Anglophone", "Petit dej", "Images/banana-bread.jpg", "https://www.marmiton.org/recettes/recette_cake-a-la-banane-banana-bread-usa_12042.aspx"),
("Gaufres salées (américain)", "Anglophone", "Petit dej", "Images/Gaufres salées à l'oeuf poché et au bacon .jpg", "https://www.cuisineaz.com/recettes/gaufres-salees-a-l-oeuf-poche-et-au-bacon-87962.aspx"),
("Pancakes américains", "Anglophone", "Petit dej", "Images/pancakes-a-l'americaine.jpg", "https://www.marmiton.org/recettes/recette_pancakes-americains_33697.aspx"),
("Smoothie fraise (américain)", "Anglophone", "Petit dej", "Images/Smoothie fraise, mûre, sirop d'érable.jpg", "https://www.cuisineaz.com/recettes/smoothie-fraise-mure-sirop-d-erable-64787.aspx"),
("Salade de fruits (américain)", "Anglophone", "Petit dej", "Images/Salade de fruits aux corn-flakes.jpg", "https://www.cuisineaz.com/recettes/salade-de-fruits-aux-corn-flakes-83196.aspx"),
("Oeufs brouillés (américain)", "Anglophone", "Petit dej", "Images/Oeufs brouillés .jpg", "https://www.marmiton.org/recettes/recette_oeufs-brouilles-nature_30569.aspx"),
("Muffins aux myrtilles (américain)", "Anglophone", "Petit dej", "Images/Muffins aux myrtilles.jpg", "https://www.marmiton.org/recettes/recette_muffins-aux-myrtilles_41510.aspx"),
("Gaufres au sucre (américain)", "Anglophone", "Petit dej", "Images/gaufres au sucre.jpg", "https://www.marmiton.org/recettes/recette_gaufres-sucrees-ou-salees_22258.aspx"),


("Huevos rancheros", "Mexicain", "Petit dej", "Images/Huevos rancheros.jpg", "https://www.lesoeufs.ca/recettes/huevos-rancheros"),
("Chilaquiles", "Mexicain", "Petit dej", "Images/Chilaquiles.jpg", "https://www.cuisineaz.com/recettes/chilaquiles-102135.aspx"),
("Haricots au chili", "Mexicain", "Petit dej", "Images/Haricote au chili.jpg", "https://www.marmiton.org/recettes/recette_chili-con-carne-facile_15415.aspx"),


("Gyozas (japonais)", "Asiatique", "Entree", "Images/Gyozas.jpg", "https://www.marmiton.org/recettes/recette_veritables-raviolis-japonais-de-a-a-z-gyoza_166959.aspx"),
("Ebi mayo (japonais)", "Asiatique", "Entree", "Images/Ebi mayo.jpg", "https://www.ptitchef.com/recettes/entree/ebi-mayo-crevette-mayonnaise-a-la-maniere-izakaya-un-classique-japonais-fid-614923"),
("Salade de chou (japonais)", "Asiatique", "Entree", "Images/Salade de chou à la japonaise croquante.jpg", "https://www.ptitchef.com/recettes/entree/salade-de-chou-japonaise-fid-1513410"),
("Beignet de crevette  (japonais)", "Asiatique", "Entree", "Images/Beignet de crevette.jpg", "https://www.cuisineaz.com/recettes/beignets-de-crevettes-51828.aspx"),
("Tataki de boeuf(japonais)", "Asiatique", "Entree", "Images/Tataki de boeuf et légumes.jpg", "https://www.ptitchef.com/recettes/entree/tataki-de-boeuf-legumes-a-la-japonaise-fid-36584"),
("Sushis au saumon (japonais)", "Asiatique", "Entree", "Images/Sushis au saumon.jpg", "https://www.atelierdeschefs.fr/fr/recette/12447-sushi-de-saumon.php"),


("Brochette de crevettes (chinois)", "Asiatique", "Entree", "Images/Brochette de crevettes.jpg", "https://www.cuisineaz.com/recettes/brochette-de-crevettes-marinees-80083.aspx"),
("Mini-rouleaux de printemps (chinois)", "Asiatique", "Entree", "Images/Mini-rouleaux de printemps.jpg", "https://www.cuisineactuelle.fr/recettes/mini-rouleaux-de-printemps-a-la-crevette-194445"),
("Nems au crabe (chinois)", "Asiatique", "Entree", "Images/Nems au crabe.jpg", "https://www.marmiton.org/recettes/recette_nems-au-crabe-recette-vietnamienne-sauce_26876.aspx"),
("Nems aux crevettes (chinois)", "Asiatique", "Entree", "Images/Nems aux crevettes.jpg", "https://www.cuisineactuelle.fr/recettes/nems-aux-crevettes-207241"),
("Bouchées vapeur aux légumes (chinois)", "Asiatique", "Entree", "Images/BBouchées vapeur aux légumes.jpg", "https://www.cuisineaz.com/recettes/bouchees-vapeur-aux-legumes-71572.aspx"),
("Wok de vermicellesnoises (chinois)", "Asiatique", "Entree", "Images/Wok de vermicelles chinoises.jpg", "https://www.ptitchef.com/recettes/plat/wok-de-vermicelles-de-riz-sautees-aux-petits-legumes-et-poulet-fid-670153"),


("Bibimbap (coréen)", "Asiatique", "Entree", "Images/Bibimbap.jpg", "https://www.atelierdeschefs.fr/fr/recette/13601-bibimbap-coreen.php"),
("Crêpes aux légumes (coréen)", "Asiatique", "Entree", "Images/Crêpes aux légumes.jpg", "https://www.cuisineaz.com/recettes/crepes-de-legumes-46307.aspx"),
("Mandus (coréen)", "Asiatique", "Entree", "Images/Mandus.jpg", "https://www.cuisineaz.com/recettes/mandus-coreens-raviolis-a-la-viande-79364.aspx"),
("Salade de carrottes (coréen)", "Asiatique", "Entree", "Images/Salade de carrottes.jpg", "https://www.cuisineaz.com/recettes/salade-de-carottes-coreenne-79377.aspx"),
("Chou fermenté épicé (coréen)", "Asiatique", "Entree", "Images/Chou fermenté épicé.jpg", "https://www.cuisineaz.com/recettes/chou-fermente-epice-a-la-coreenne-79367.aspx"),
("Brochettes de viande (coréen)", "Asiatique", "Entree", "Images/Brochettes de viande aux légumes.jpg", "https://www.marmiton.org/recettes/recette_brochettes-boeuf-poulet-et-legumes_80176.aspx"),
("Beignets de bettrave (coréen)", "Asiatique", "Entree", "Images/Beignets de betterave et de radis blanc.jpg", "https://madame.lefigaro.fr/recettes/beignets-de-betterave-et-de-radis-blanc-140120-179126"),


("Naans (indien)", "Asiatique", "Entree", "Images/Naans.jpg", "https://www.750g.com/comment-faire-des-naans-r200171.htm"),
("Samoussa (indien)", "Asiatique", "Entree", "Images/Samoussa.jpg", "https://www.marmiton.org/recettes/recette_samoussa-au-boeuf-rapides_171841.aspx"),
("Raïta aux poivrons (indien)", "Asiatique", "Entree", "Images/Raïta aux poivrons.jpg", "http://www.certiferme.com/recette/recette-raita-de-poivrons-14215.html"),
("Chutney de tomates (indien)", "Asiatique", "Entree", "Images/Chutney de tomates.jpg", "https://www.cuisineactuelle.fr/recettes/chutney-de-tomates-204988"),
("Empanadas au chutney (indien)", "Asiatique", "Entree", "Images/Empanadas au chutney de pommes, oignons et curry.jpg", "https://amandebasilic.com/empanadas-au-chutney-de-pommes-oignons-et-curry/"),
("Rolls aux légumes (indien)", "Asiatique", "Entree", "Images/Rolls aux légumes ou viande.jpg", "https://123veggie.fr/recette/rolls-aux-legumes/"),
("Oignons bhaji (indien)", "Asiatique", "Entree", "Images/Oignons bhaji.jpg", "https://ricardocuisine.com/recettes/367-bhaji-a-l-oignon-beignets-indiens-a-l-oignon"),
("Pannacotta (indien)", "Asiatique", "Entree", "Images/Pannacotta.jpg", "https://www.marmiton.org/recettes/recette_panna-cotta_17991.aspx"),


("Oeuf cocotte","Francais", "Entree","Images/Oeuf cocotte.jpg","https://www.marmiton.org/recettes/recette_oeufs-cocottes_66170.aspx"),
("Farandole d'oeufs mimosa","Francais", "Entree","Images/Farandole d'oeufs mimosa.jpg","https://www.marmiton.org/recettes/recette_oeufs-mimosa_28602.aspx"),
("Salade niçoise","Francais", "Entree","Images/Salade niçoise.jpg","https://www.marmiton.org/recettes/recette_salade-nicoise-l-authentique-nicoise_30330.aspx"),
("Terrine de lapin","Francais", "Entree","Images/Terrine de lapin aux noisettes.jpg","https://www.cuisineaz.com/recettes/terrine-de-lapin-aux-noisettes-91306.aspx"),
("Pâté en croûte aux morilles","Francais", "Entree","Images/Pâté en croûte aux morilles.jpg","https://www.regal.fr/recettes/entrees/pate-en-croute-aux-morilles-6623"),
("Cervelas brioché", "Entree","Images/Cervelas brioché.jpg","https://www.marmiton.org/recettes/recette_cervelas-brioche_56832.aspx"),
("Tarte flambée","Francais", "Entree","Images/Tarte flambée.jpg","https://www.marmiton.org/recettes/recette_flammekueche-ou-tarte-flambee-alsace_11538.aspx"),
("Salade de chèvre chaud","Francais", "Entree","Images/Salade de chèvre chaud aux noids.jpg","https://www.aux-fourneaux.fr/salade-de-chevre-chaud-aux-noix-21482/"),


("Carpaccio de bresaola au pesto", "Italien", "Entree", "Images/Carpaccio de bresaola au pesto.jpg", "https://www.cuisineaz.com/recettes/carpaccio-de-bresaola-au-pesto-10239.aspx"),
("Asperges à la milanaise", "Italien", "Entree", "Images/Asperges à la milanaise.jpg", "https://www.cuisineaz.com/recettes/asperges-a-la-milanaise-63143.aspx"),
("Frittata de pommes de terre", "Italien", "Entree", "Images/Frittata de pommes de terre aux courgettes.jpg", "https://www.cuisineaz.com/recettes/tortilla-frittata-de-pommes-de-terre-aux-courgettes-85956.aspx"),
("Antipasti de poivrons grillés", "Italien", "Entree", "Images/Antipasti de poivrons grillés.jpg", "https://www.cuisineaz.com/recettes/antipasti-de-poivrons-grilles-85958.aspx"),
("Aubergines à la parmigiana", "Italien", "Entree", "Images/Aubergines à la parmigiana.jpg", "https://www.marmiton.org/recettes/recette_aubergines-a-la-parmigiana_36293.aspx"),
("Minestrone de macaroni", "Italien", "Entree", "Images/minestrone de macaronie.jpg", "https://www.cuisineaz.com/recettes/minestrone-de-macaroni-28816.aspx"),
("Calzone aux tomates, jambon de Parme à la mozzarella", "Italien", "Entree", "Images/Calzone aux tomates.jpg", "https://www.cuisineaz.com/recettes/calzone-aux-tomates-jambon-de-parme-a-la-mozzarella-82325.aspx"),
("Salade de melon", "Italien", "Entree", "Images/Salade de melon et jambon de Parme.jpg", "https://www.cuisineaz.com/recettes/salade-de-melon-et-jambon-de-parme-12037.aspx"),
("Bruschetta d'été ", "Italien", "Entree", "Images/Bruschetta d'été aux tomates et mozzarella.jpg", "https://www.marmiton.org/recettes/recette_bruschetta-a-la-mozzarella_30276.aspx"),
("Artichauts à la vénitienne", "Italien", "Entree", "Images/Artichauts à la vénitienne.jpg", "https://www.quatresaisonsaujardin.com/artichauts-a-la-venitienne/"),


("Tourte champignon poulet (anglais)", "Anglophone", "Entree", "Images/tourte-poulet-champignons.jpg", "https://www.papillesetpupilles.fr/2021/03/tourte-au-poulet-et-aux-champignons.html/"),
("Pâté de volaille en croûte (angliais", "Anglophone", "Entree", "Images/Pâté de volaille en croûte.jpg", "https://www.ptitchef.com/recettes/plat/pate-de-volaille-en-croute-fid-1197532"),
("Tourte de la mer (anglais)", "Anglophone", "Entree", "Images/Tourte de la mer.jpg", "https://www.marmiton.org/recettes/recette_tourte-aux-fruits-de-mer_23794.aspx"),
("Soupe à l'oignon (anglais)", "Anglophone", "Entree", "Images/Soupe à l'oignon gratinée au comté.jpg", "https://www.ptitchef.com/recettes/entree/soupe-a-l-oignon-gratinee-au-comte-fid-1491572"),
("Coleslaw (anglais)", "Anglophone", "Entree", "Images/Coleslaw.jpg", "https://www.marmiton.org/recettes/recette_coleslaw-facile_28532.aspx"),
("Cupcakes au saumon fumé (anglais)", "Anglophone", "Entree", "Images/Cupcakes au saumon fumé .jpg", "https://www.cuisineactuelle.fr/recettes/cupcakes-au-saumon-fume-241656"),
("Welsch Rarebit (anglais)", "Anglophone", "Entree", "Images/Welsch Rarebit.jpg", "https://www.marmiton.org/recettes/recette_welsh-rarebit-anglais_41793.aspx"),
("Trempette aux crevettes (anglais)", "Anglophone", "Entree", "Images/Trempette aux crevettes.jpg", "https://www.lesrecettesdecaty.com/fr/recettes/sauces-et-trempettes/trempette-aux-crevettes-nordiques/"),
("Trempette aux épinards (anglais)", "Anglophone", "Entree", "Trempette aux épinards et fromage blanc.jpg", "https://madame.lefigaro.fr/recettes/trempette-epinards-fromage-blanc-090701-199497"),


("Coleslaw aux cranberries (américain)", "Anglophone", "Entree", "Images/CranberryColeslaw.jpg", "https://madame.lefigaro.fr/recettes/coleslaw-leger-cranberries-210409-6889"),
("Crab Rolls (américain)", "Anglophone", "Entree", "Images/Crab Rolls.jpg", "https://madame.lefigaro.fr/recettes/crab-rolls-040414-847770"),
("Muffins au jambon et au fromage (américain)", "Anglophone", "Entree", "Images/Muffins au jambon et au fromage.jpg", "https://cuisine.journaldesfemmes.fr/recette/307032-muffins-jambon-fromage"),
("Milkshake de concombre (américain)", "Anglophone", "Entree", "Images/Milkshake de concombre mentholé.jpg", "https://www.cuisineactuelle.fr/recettes/milk-shake-de-concombre-203344"),
("Fèves fraîches en salade (américain)", "Anglophone", "Entree", "Images/Fèves fraîches en salade.jpg", "https://chefsimon.com/gourmets/chef-simon/recettes/salade-de-feves-a-la-ciboulette"),
("Pain de maïs (américain)", "Anglophone", "Entree", "Images/Pain de maïs.jpg", "https://www.marmiton.org/recettes/recette_pain-de-mais-etats-unis_17167.aspx"),
("Croquettes de polenta (américain)", "Anglophone", "Entree", "Images/Croquettes de polenta.jpg", "https://cuisine.journaldesfemmes.fr/recette/356264-croquettes-de-polenta"),


("Bouchés de tortilla", "Mexicain", "Entree", "Images/Bouchés de tortilla.jpg", "https://www.ptitchef.com/recettes/aperitif/bouchees-de-tortillas-a-la-dinde-et-a-l-avocat-fid-258235"),
("Céleri-branche en salade", "Mexicain", "Entree", "Images/Céleri-branche en salade.jpg", "https://www.marmiton.org/recettes/recette_salade-de-celeri-branche-pommes-noix-et-des-de-fromage_66202.aspx"),
("Enchiladas", "Mexicain", "Entree", "Images/Enchiladas.jpg", "https://www.cuisineactuelle.fr/recettes/enchiladas-mexicaines-297153"),
("Guacamole au crabe frais", "Mexicain", "Entree", "Images/Guacamole au crabe frais.jpg", "https://www.marmiton.org/recettes/recette_guacamole-au-crabe_19331.aspx"),
("Mesclun au guacamole", "Mexicain", "Entree", "Images/Mesclun au guacamole.jpg", "https://madame.lefigaro.fr/recettes/mesclun-guacamole-231002-202005"),
("Purée de tomates mexicaine", "Mexicain", "Entree", "Images/Purée de tomates mexicaine.jpg", "https://madame.lefigaro.fr/recettes/puree-de-tomates-mexicaine-150501-198335"),
("Salade de pomme fruit", "Mexicain", "Entree", "Images/Salade de pomme fruit.jpg", "https://www.750g.com/salade-de-fruits-a-la-mexicaine-r14894.htm"),
("Salade exotique", "Mexicain", "Entrée", "Images/Salade exotique à l'avocat et au maïs.jpg", "https://cuisine.journaldesfemmes.fr/recette/1001533-salade-exotique-a-l-avocat-croustillant-de-mais"),


("Maki (Japonais)", "Asiatique", "Plat", "Images/Maki.jpg", "https://www.marmiton.org/recettes/recette_maki-avocat-saumon-crevette-ou-surimi_168785.aspx"),
("Sushi (Japonais)", "Asiatique", "Plat", "Images/Sushi.jpg", "https://www.marmiton.org/recettes/recette_sushi-californien-maki-inverse_64650.aspx"),
("Onigiri (Japonais)", "Asiatique", "Plat", "Images/Onigiri.jpg", "https://www.marmiton.org/recettes/recette_onigiri-japon_29656.aspx"),
("Yakitori (Japonais)", "Asiatique", "Plat", "Images/Yakitori.jpg", "https://www.marmiton.org/recettes/recette_yakitori-boeuf-au-fromage-rapide_68293.aspx"),
("Chirashi (Japonais)", "Asiatique", "Plat", "Images/Chirashi.jpeg", "https://www.cuisineaz.com/recettes/chirashi-saumon-et-avocat-85199.aspx"),

("Wok de poulet(Chinois)", "Asiatique", "Plat", "Images/Wok de poulet au soja et chou blanc.jpeg", "https://www.marmiton.org/recettes/recette_wok-de-poulet-a-la-pate-de-curry-jaune-graines-de-sesame-et-petits-legumes_69320.aspx"),
("Poulet caramel(Chinois)", "Asiatique", "Plat", "Images/Poulet caramel au sésame.jpg", "https://www.marmiton.org/recettes/recette_poulet-sesame-chinois_35998.aspx"),
(" Nouilles sautées (Chinois)", "Asiatique", "Plat", "Images/Nouilles sautées au poulet et au sésame.jpg", "https://www.marmiton.org/recettes/recette_nouilles-sautees-au-poulet-caramelise_87366.aspx"),
("Soupe chinoise au poulet (Chinois)", "Asiatique", "Plat", "Images/Soupe chinoise au poulet.jpg", "https://www.marmiton.org/recettes/recette_soupe-chinoise-au-poulet_31812.aspx"),
("Brochettes de canard (Chinois)", "Asiatique", "Plat", "Images/Brochettes de canard à l'orange.jpg", "https://www.marmiton.org/recettes/recette_brochette-de-canard-marine-a-l-orange_41820.aspx"),
("Nouilles au boeuf épicé(Chinois)", "Asiatique", "Plat", "Images/Nouilles au boeuf épicé, champignons et noix de cajou.jpg", "https://www.audinette.com/nouilles-sautees-aux-noix-de-cajou/"),
("Brochettes de boeuf(Chinois)", "Asiatique", "Plat", "Images/Brochettes de boeuf à la citronnelle.jpg", "https://www.marmiton.org/recettes/recette_boeuf-citronnelle-en-brochettes_14380.aspx"),
("Riz cantonais au porc (Chinois)", "Asiatique", "Plat", "Images/Riz cantonais au porc et aux légumes, sauce nikkei.jpg", "https://www.regal.fr/inspiration/recette-de-chef/riz-cantonais-au-porc-et-aux-legumes-sauce-nikkei-15106"),
(" Porc au caramel (Chinois)", "Asiatique", "Plat", "Images/Porc au caramel.jpg", "https://www.regal.fr/porc-au-caramel-12584"),
("Crevettes au caramel (Chinois)", "Asiatique", "Plat", "Images/Crevettes au poivre et au caramel.jpeg", "https://www.marmiton.org/recettes/recette_crevettes-au-caramel_41449.aspx"),
(" Riz cantonnais (Chinois)", "Asiatique", "Plat", "Images/Riz cantonnais.jpg", "https://www.marmiton.org/recettes/recette_riz-cantonnais-facile_168829.aspx"),


("Udon (coréen)", "Asiatique", "Plat", "Images/Udon.jpg", "https://www.regal.fr/recettes/plats/udon-8404"),
("Ramen (coréen)", "Asiatique", "Plat", "Images/Ramen.jpg", "https://www.marmiton.org/recettes/recette_ramens-au-boeuf_218682.aspx"),
("Soe Galbijim (coréen)", "Asiatique", "Plat", "Images/Soe Galbijim.jpg", "https://www.750g.com/soe-galbijim-galbi-jim-ou-boeuf-mijote-a-la-coreenne-r202758.htm"),
("Japchae (coréen)", "Asiatique", "Plat", "Images/Japchae.png", "https://www.regal.fr/recettes/plats/japchae-par-pierre-sang-boyer-15182"),
("Sigeumchi namul (coréen)", "Asiatique", "Plat", "Images/Sigeumchi namul.jpg", "https://www.750g.com/sigeumchi-namul-epinards-aux-graines-de-sesame-a-la-coreenne-r202650.htm"),
("Haemul-pajeon (coréen)", "Asiatique", "Plat", "Images/Haemul-pajeon.png", "https://www.750g.com/haemul-pajeon-crepe-coreenne-a-la-ciboule-et-aux-fruits-de-mer-r202651.htm"),
("Dakgangjeong (coréen)", "Asiatique", "Plat", "Images/Dakgangjeong.jpg", "https://www.750g.com/dakgangjeong-le-poulet-frit-coreen-r208241.htm"),
("Pa Muchim (coréen)", "Asiatique", "Plat", "Images/Pa Muchim.jpg", "https://www.750g.com/pa-muchim-r202851.htm"),
("Hotteok (coréen)", "Asiatique", "Plat", "Images/Hotteok.jpg", "https://www.750g.com/hotteok-r202849.htm"),
("Bulgoji (coréen)", "Asiatique", "Plat", "Images/Bulgoji.jpg", "https://www.750g.com/bulgogi-r44980.htm"),
("Kimchi (coréen)", "Asiatique", "Plat", "Images/Kimchi.jpg", "https://www.750g.com/baechu-kimchi-r202852.htm"),


("Biryani (indien)", "Asiatique", "Plat", "Images/Biryani.jpg", "https://www.750g.com/byriani-aux-legumes-r203039.htm"),
("Kottu rotti (indien)", "Asiatique", "Plat", "Images/Kothu rotti.jpg", "https://www.simpleetgourmand.fr/recettes/kottu-paratha/"),
("Puttu (indien)", "Asiatique", "Plat", "Images/Puttu.jpg", "https://stringfixer.com/fr/Puttu"),
("Dosa (indien)", "Asiatique", "Plat", "Images/Dosa.jpg", "https://www.750g.com/rava-dosa-plat-indien-r32601.htm"),
("Poulet tandoori (indien)", "Asiatique", "Plat", "Images/Poulet tandoori.jpg", "https://www.750g.com/poulet-tandoori-r60041.htm"),
("Dahl (indien)", "Asiatique", "Plat", "Images/Dahl.jpg", "https://www.750g.com/dahl-de-lentilles-corail-r202235.htm"),
("Riz basmati au curry (indien)", "Asiatique", "Plat", "Images/Riz basmati au curry.jpg", "https://www.marmiton.org/recettes/recette_curry-d-agneau-a-l-indienne_14942.aspx"),
("Epinards mughlai (indien)", "Asiatique", "Plat", "Images/Epinards mughlai.jpeg", "https://cuisine.journaldesfemmes.fr/recette/343747-epinards-mughlai"),
("Pois gourmands (indien)", "Asiatique", "Plat", "Images/Pois gourmands aux tomates et épices.jpg", "https://cuisine.journaldesfemmes.fr/recette/343318-pois-gourmands-aux-tomates-et-epices"),
("Curry de poisson(indien)", "Asiatique", "Plat", "Images/Curry de poisson au lait de coco.jpg", "https://www.750g.com/mijote-de-poisson-au-curry-et-lait-de-coco-r90693.htm"),


("Boeuf bourguignon", "Francais", "Plat", "Images/Boeuf bourguignon.jpg", "https://www.marmiton.org/recettes/recette_boeuf-bourguignon-rapide_19218.aspx"),
("Magret de canard", "Francais", "Plat", "Images/magret de canard.jpg", "https://www.marmiton.org/recettes/recette_magrets-de-canard-au-miel_11774.aspx"),
("Frites", "Francais", "Plat", "Images/Frites.jpg", "https://www.marmiton.org/recettes/recette_bonnes-frites_15755.aspx"),
("Croque monsieur", "Francais", "Plat", "Images/Croque monsieur.jpg", "https://www.marmiton.org/recettes/recette_croque-monsieur-a-la-creme_14223.aspx"),
("Omelette", "Francais", "Plat", "Images/Omelette.jpg", "https://www.marmiton.org/recettes/recette_omelette-aux-pommes-de-terre-et-lardons_19387.aspx"),
("Cordon bleue", "Francais", "Plat", "Images/Cordon bleue.jpg", "https://www.marmiton.org/recettes/recette_cordon-bleu_27731.aspx"),
("Tomate farcie", "Francais", "Plat", "Images/Tomate farcie.png", "https://www.marmiton.org/recettes/recette_tomates-farcies-facile_63622.aspx"),
("Raclette", "Francais", "Plat", "Images/raclette.jpg", "https://www.marmiton.org/recettes/recette_raclette-recette-originale_13233.aspx"),
("Soupe aux légumes", "Francais", "Plat", "Images/Soupe aux légumes.jpg", "https://www.marmiton.org/recettes/recette_soupe-aux-7-legumes_65063.aspx"),
("Purée de pomme de terre", "Francais", "Plat", "Images/Purée de pomme de terre.jpg", "https://www.marmiton.org/recettes/recette_puree-de-pommes-de-terre-maison_28054.aspx"),


("Pizza", "italien", "Plat", "Images/pizza.png", "https://www.marmiton.org/recettes/recette_pate-a-pizza-fine_29544.aspx"),
("Spaghetti bolognaise", "italien", "Plat", "Images/Spaghetti bolognaise.jpg", "https://www.marmiton.org/recettes/recette_spaghetti-bolognaise_19840.aspx"),
("Lasagne", "italien", "Plat", "Images/lasagne.jpg", "https://www.marmiton.org/recettes/recette_lasagnes-a-la-bolognaise_18215.aspx"),
("Osso-bucco", "italien", "Plat", "Images/Osso-bucco.jpeg", "https://www.marmiton.org/recettes/recette_osso-bucco-milanaise_26684.aspx"),
("Raviolies", "italien", "Plat", "Images/Ravioles.jpg", "https://www.750g.com/ravioles-a-la-ricotta-et-basilic-r98162.htm"),
("Pâtes carbonara", "italien", "Plat", "Images/Pâtes carbonara.jpg", "https://www.marmiton.org/recettes/recette_pates-carbonara_21229.aspx"),
("Pâtes pesto", "italien", "Plat", "Images/âtes pesto.jpg", "https://www.750g.com/pates-au-pesto-de-basilic-r14268.htm"),


("Burger (anglais)", "Anglophone", "Plat", "Images/Burger (anglais).jpg", "https://www.750g.com/le-burger-750g-r88257.htm"),
("Hot dog (anglais)", "Anglophone", "Plat", "Images/Hot dog.jpg", "https://www.marmiton.org/recettes/recette_hot-dog-new-yorkais_47180.aspx"),
("Croque-monsieur anglais", "Anglophone", "Plat", "Images/Croque-monsieur anglais au thon.jpg", "https://www.marmiton.org/recettes/recette_croque-monsieur-anglais-au-thon_47879.aspx"),
("Fish and Chips", "Anglophone", "Plat", "Images/Fish and Chips.jpg", "https://www.marmiton.org/recettes/recette_fish-and-chips-la-vraie-pate-a-friture-anglaise_22308.aspx"),
("Filet de cabillaud à l'anglaise", "Anglophone", "Plat", "Images/Filet de cabillaud à l'anglaise.jpg", "https://www.marmiton.org/recettes/recette_filet-de-cabillaud-a-l-anglaise_14116.aspx"),
("Poulet et bœuf,cock and bull (anglais)", "Anglophone", "Plat", "Images/Poulet et boeuf, sauce poivre et fromage.jpg", "https://www.marmiton.org/recettes/recette_sauce-au-poivre-toute-simple-au-cooking-chef_382968.aspx"),
("Kedgeree (anglais)", "Anglophone", "Plat", "Images/Kedgeree.jpg", "https://www.marmiton.org/recettes/recette_kedgeree_24598.aspx"),
("Agneau de la ferme (anglais)", "Anglophone", "Plat", "Images/Agneau de la ferme et sauce verte.jpg", "https://www.marmiton.org/recettes/recette_sauce-verte-pour-viandes-ou-poissons_53672.aspx"),
("Le « Sunday roast » (anglais)", "Anglophone", "Plat", "Images/Sunday roast.jpg", "https://in-my-cuisine.com/sunday-roast/"),
("« Bangers and mash » (anglais)", "Anglophone", "Plat", "Images/Bangers and mash.jpg", "https://www.demotivateur.fr/food/bangers-and-mash-18878"),
("Le « Toad in the hole » (anglais)", "Anglophone", "Plat", "Images/Toad in the hole.jpg", "https://www.cuisineaz.com/recettes/toad-in-the-hole-112890.aspx"),
("Le « Welsh rarebit » (anglais)", "Anglophone", "Plat", "Images/Welsh rarebit.jpg", "https://www.marmiton.org/recettes/recette_welsh-rarebit-anglais_41793.aspx"),
("Le « Haggis » (anglais)", "Anglophone", "Plat", "Images/Haggis.jpg", "https://www.marmiton.org/recettes/recette_haggis-ecossais_53122.aspx"),
("Le « Bubble and Squeak (anglais)", "Anglophone", "Plat", "Images/Bubble and Squeak.jpg", "https://www.cuisineactuelle.fr/recettes/bubble-and-squeak-147898"),


("Burger (américain)", "Anglophone", "Plat", "Images/Burger.jpg", "https://www.cuisineaz.com/recettes/burger-au-bacon-et-au-cheddar-87196.aspx"),
("Hot dog (américain)", "Anglophone", "Plat", "Images/Hot dog.jpg", "https://www.cuisineaz.com/recettes/hot-dogs-5183.aspx"),
("Spare ribs (américain)", "Anglophone", "Plat", "Images/Spare ribs.jpg", "https://www.cuisineaz.com/recettes/spare-ribs-2198.aspx"),
("Buffalo chicken wings (américain)", "Anglophone", "Plat", "Images/buffalo chicken wings.jpg", "https://www.marmiton.org/recettes/recette_chicken-wings_371857.aspx"),
("Soupe au poulet (américain)", "Anglophone", "Plat", "Soupe au poulet.jpg", "https://www.marmiton.org/recettes/recette_soupe-de-poulet-new-york-style_23072.aspx"),
("Cornbread (américain)", "Anglophone", "Plat", "Images/Cornbread.jpg", "https://www.cuisineaz.com/recettes/cornbread-pain-de-mais-59361.aspx"),
("Nachos façon mexicaine américaine", "Anglophone", "Plat", "Images/Nachos façon mexicaine américaine.jpg", "https://www.recette-americaine.com/plat/nachos-facon-mexicaine.php#gref"),
("Jalapeno poppers (américain)", "Anglophone", "Plat", "Images/Jalapeno poppers.jpg", "https://www.marmiton.org/recettes/recette_jalapenos-poppers-beignets-de-piments-au-fromage_46885.aspx"),
("Homard à l'américaine", "Anglophone", "Plat", "Images/Homard à l'américaine avec légumes.jpg", "https://www.cuisineaz.com/recettes/homard-a-l-americaine-avec-legumes-et-fumet-de-poisson-28613.aspx"),
("Dinde de Thanksgiving (américain)", "Anglophone", "Plat", "Images/Dinde de Thanksgiving.jpg", "https://www.cuisineaz.com/recettes/dinde-de-thanksgiving-aux-legumes-84058.aspx"),


("Chili con carne", "Mexicain", "Plat", "Images/chili cone carne.jpeg", "https://www.marmiton.org/recettes/recette_chili-con-carne-facile_15415.aspx"),
("Tortilla", "Mexicain", "Plat", "Images/tortilla.jpeg", "https://www.marmiton.org/recettes/recette_sandwich-de-tortillas_48630.aspx"),
("Fajitas", "Mexicain", "Plat", "Images/Fajitas.png", "https://www.marmiton.org/recettes/recette_fajitas-de-poulet_27688.aspx"),
("La quesadilla", "Mexicain", "Plat", "Images/La quesadilla.png", "https://www.marmiton.org/recettes/recette_quesadillas_23350.aspx"),
("L'enchilada", "Mexicain", "Plat", "Images/L'enchilada.jpg", "https://www.marmiton.org/recettes/recette_enchiladas-franchouillards_32979.aspx"),
("Les tamales", "Mexicain", "Plat", "Images/Les tamales.jpg", "https://www.750g.com/tamales-au-porc-r52088.htm"),
("Les chilaquiles", "Mexicain", "Plat", "Images/Les chilaquiles.jpg", "https://www.cuisineaz.com/recettes/chilaquiles-102135.aspx"),
("Les tostadas", "Mexicain", "Plat", "Images/Les tostadas.jpg", "https://www.marmiton.org/recettes/recette_tostadas_18470.aspx"),
("Le ceviche", "Mexicain", "Plat", "Images/Le ceviche.jpeg", "https://www.marmiton.org/recettes/recette_ceviche-mexique_13102.aspx"),
("Chile en nogada", "Mexicain", "Plat", "Images/Chile en nogada.jpg", "https://www.cuisineaz.com/recettes/chiles-en-nogada-ou-poivrons-mexicains-farcis-a-la-viande-et-a-la-grenade-90349.aspx"),


("Tiramisu (Japonais)", "Asiatique", "Dessert", "Images/Tiramisu.jpg.crdownload", "https://www.marmiton.org/recettes/recette_tiramisu-au-the-vert-matcha_329724.aspx"),
("Matcha (Japonais)", "Asiatique", "Dessert", "Images/Tiramisu.jpg.crdownload", "https://www.marmiton.org/recettes/recette_madeleine-au-the-matcha-light_339915.aspx"),
("Dango (Japonais)", "Asiatique", "Dessert", "Images/Tiramisu.jpg.crdownload", "https://www.marmiton.org/recettes/recette_les-vrais-dango-et-daifuku-japonais_319196.aspx"),
("Chiffon cake (Japonais)", "Asiatique", "Dessert", "Images/Tiramisu.jpg.crdownload", "https://www.cuisineaz.com/recettes/gateau-mousseline-chiffon-cake-78521.aspx"),
("Ichigo daifuku (Japonais)", "Asiatique", "Dessert", "Images/Ichigo daifuku.jpg", "https://www.marmiton.org/recettes/recette_daifuku-au-fraise_530644.aspx"),
("Kakigori (Japonais)", "Asiatique", "Dessert", "Images/Ichigo daifuku.jpg", "https://www.cuisine-japon.fr/kakigori-glace-pilee-japonaise/"),
("Chigiri pan (Japonais)", "Asiatique", "Dessert", "Images/Chigiri pan.jpg", "https://www.cestmafournee.com/2017/03/le-chigiri-pan.html"),
("Dorayaki (Japonais)", "Asiatique", "Dessert", "Images/Dorayaki.jpeg", "https://www.marmiton.org/recettes/recette_dorayaki_383870.aspx"),
("Momiji manju (Japonais)", "Asiatique", "Dessert", "Images/Momiji manju.jpg", "http://momiji.fr/la-recette-du-momiji-manju-le-gateau-automnal-de-miyajima/"),
("Taiyaki (Japonais)", "Asiatique", "Dessert", "Images/Taiyaki.jpg", "https://www.marmiton.org/recettes/recette_taiyaki_392188.aspx"),
("Mochi (Japonais)", "Asiatique", "Dessert", "Images/Mochi.jpg", "https://www.marmiton.org/recettes/recette_mochi-ice-cream_230033.aspx"),


("Kumquats confits (Chinois)", "Asiatique", "Dessert", "Images/Kumquats confits.jpg", "https://www.marmiton.org/recettes/recette_kumquats-confits-a-servir-avec-le-foie-gras_43409.aspx"),
("Beignets de sésame (Chinois)", "Asiatique", "Dessert", "Images/Beignets de sésame.jpg", "https://www.marmiton.org/recettes/recette_beignets-au-sesame-chine_16764.aspx"),
("Gelée de litchis chinoise", "Asiatique", "Dessert", "Images/Gelée de litchis chinoise.jpg", "https://www.cuisineaz.com/recettes/gelee-de-litchis-chinoise-92090.aspx"),
("Pudding chinois à la noix de coco", "Asiatique", "Dessert", "Images/Pudding chinois à la noix de coco.jpeg", "https://www.cuisineaz.com/recettes/pudding-chinois-a-la-noix-de-coco-92091.aspx"),
("Fortune cookies (Chinois)", "Asiatique", "Dessert", "Images/Fortune cookies.jpg", "https://www.cuisineaz.com/recettes/fortune-cookies-48703.aspx"),
("Riz gluant au lait de coco et à la mangue (Chinois)", "Asiatique", "Dessert", "Images/Riz gluant au lait de coco et à la mangue.jpg", "https://www.cuisineaz.com/recettes/riz-gluant-au-lait-de-coco-et-a-la-mangue-61798.aspx"),
("Nougat chinois", "Asiatique", "Dessert", "Images/Nougat chinois.jpg", "https://www.cuisineaz.com/recettes/nougat-chinois-95614.aspx"),


("Hwajeon (coréen)", "Asiatique", "Dessert", "Images/Hwajeon.jpg", "https://kimshii.com/2012/03/gateaux-coreens-les-hwajeon-%ED%99%94%EC%A0%84.html"),
("Yakgwa (coréen)", "Asiatique", "Dessert", "", "Images/Yakgwa.jpg","https://www.750g.com/yakgwa-biscuits-frits-au-gingembre-et-au-miel-r97353.htm"),
("Gyeongdan (coréen)", "Asiatique", "Dessert", "Images/Gyeongdan.jpg", "https://kimshii.com/2013/02/patisserie-coreenne-le-gyeongdan-%EA%B2%BD%EB%8B%A8.html"),
("Hotteok (coréen)", "Asiatique", "Dessert", "Images/Hotteok.jpg", "https://www.750g.com/hotteok-r202849.htm"),
("Hodou gwaja (coréen)", "Asiatique", "Dessert", "Images/Hodou gwaja.jpg", "https://kimshii.com/2014/05/patisserie-coreenne-le-gateau-aux-noix-hodou-gwaja.html"),
("Gelée de cerises à la coréenne", "Asiatique", "Dessert", "Images/Gelée de cerises à la coréenne.jpg", "https://unflodebonneschoses.fr/gelee-de-cerises-a-la-coreenne-aengdu-pyon/"),
("Hobaktteaok (coréen)", "Asiatique", "Dessert", "Images/Hobaktteaok.png", "https://www.750g.com/hobaktteaok-r203447.htm"),
("Kkwabaegi (coréen)", "Asiatique", "Dessert", "Images/Kkwabaegi.jpg", "https://www.marmiton.org/recettes/recette_beignets-torsades-coreens-kkwabaegi_343964.aspx"),


("Kesari (indien)", "Asiatique", "Dessert", "Images/Kesari.jpg", "https://www.cuisineaz.com/recettes/kesari-8047.aspx"),
("Yaourt à l'indienne", "Asiatique", "Dessert", "Images/Yaourt à l'indienne au safran et amandes.jpg", "https://www.cuisineaz.com/recettes/yaourt-a-l-indienne-au-safran-et-amandes-70529.aspx"),
("Riz au lait à l'orange(indien)", "Asiatique", "Dessert", "Images/Riz au lait à l'orange, au safran et aux pistaches.jpg", "https://www.cuisineaz.com/recettes/riz-au-lait-a-l-orange-au-safran-et-aux-pistaches-65716.aspx"),
("Ladoo (indien)", "Asiatique", "Dessert", "Images/Ladoo.jpg", "https://www.cuisineaz.com/recettes/ladoos-58673.aspx"),
("Bananes à l'indienne", "Asiatique", "Dessert", "Images/Bananes à l'indienne.jpg", "https://www.cuisineaz.com/recettes/bananes-a-l-indienne-8275.aspx"),
("Lassi mangue-coco (Indien)", "Asiatique", "Dessert", "Images/Lassi mangue-coco.jpg", "https://www.marmiton.org/recettes/recette_le-vrai-lassi-a-la-mangue-inde_39153.aspx"),
("Chutney indien", "Asiatique", "Dessert", "Images/Chutney indien à la pâte de tamarin.jpg", "https://www.cuisineaz.com/recettes/chutney-indien-a-la-pate-de-tamarin-54356.aspx"),
("Bouchées sucrées indiennes", "Asiatique", "Dessert", "Images/Bouchées sucrées indiennes.jpg", "https://www.cuisineaz.com/recettes/bouchees-sucrees-indiennes-15049.aspx"),
("Crème de mangue (Indien)", "Asiatique", "Dessert", "Images/Crème de mangue.png", "https://www.marmiton.org/recettes/recette_creme-de-mangue-facile-et-legere_22011.aspx"),
("Boules à la noix de coco (Indien)", "Asiatique", "Dessert", "Images/Boules à la noix de coco et safran.jpg", "https://www.cuisineaz.com/recettes/boules-a-la-noix-de-coco-et-safran-13444.aspx"),


("Gateau au chocolat", "Francais", "Dessert", "Images/Gateau au chocolat.jpg", "https://www.marmiton.org/recettes/recette_gateau-au-chocolat-fondant-rapide_166352.aspx"),
("Gateau nature", "Francais", "Dessert", "Images/Gateau nature.jpg", "https://www.marmiton.org/recettes/recette_gateau-nature_59083.aspx"),
("Cookies", "Francais", "Dessert", "Images/Cookies.jpeg", "https://www.marmiton.org/recettes/recette_cookies-aux-pepites-de-chocolat-super-moelleux_57330.aspx"),
("Beignets", "Francais", "Dessert", "Images/Beignets.jpg.crdownload", "https://www.marmiton.org/recettes/recette_beignets-de-pomme-de-mon-papi_51021.aspx"),
("Brownies", "Francais", "Dessert", "Images/Brownies.jpg", "https://www.marmiton.org/recettes/recette_brownies_16951.aspx"),
("Crêpes Suzette", "Francais", "Dessert", "Images/Crêpes Suzette.jpeg", "https://www.marmiton.org/none/philippe-etchebest-sa-recette-incroyable-de-crepes-suzette-s4035836.html"),
("Macarons", "Francais", "Dessert", "Images/Macarons.jpeg", "https://www.marmiton.org/recettes/recette_macarons-au-chocolat-maya-gold-rencontre-de-sceau_52925.aspx"),
("Tarte aux pommes", "Francais", "Dessert", "Images/Tarte aux pommes.jpg", "https://www.marmiton.org/recettes/recette_tarte-aux-pommes-a-l-alsacienne_11457.aspx"),
("Pain perdu", "Francais", "Dessert", "Images/Pain perdu.jpg", "https://www.marmiton.org/recettes/recette_pain-perdu_10975.aspx"),
("Far breton aux pruneaux", "Francais", "Dessert", "Images/Far breton aux pruneaux.jpg", "https://www.marmiton.org/recettes/recette_far-breton-aux-pruneaux_19101.aspx"),
("Crème caramel", "Francais", "Dessert", "Images/Crème caramel.jpg", "https://www.marmiton.org/recettes/recette_creme-caramel-classique_22944.aspx"),
("Baba au rhum", "Francais", "Dessert", "Images/Baba au rhum.jpg", "https://www.marmiton.org/recettes/recette_baba-au-rhum-de-la-reunion_230171.aspx"),
("Eclairs au chocolat", "Francais", "Dessert", "Images/Eclairs au chocolat.png", "https://www.marmiton.org/recettes/recette_eclairs-au-chocolat_28555.aspx"),
("Crème brûlée", "Francais", "Dessert", "Images/Crème brûlée à la vanille.jpg", "https://www.marmiton.org/recettes/recette_creme-brulee-vanille_19434.aspx"),
("Mousse au chocolat express", "Francais", "Dessert", "Images/Mousse au chocolat express.jpg", "https://www.marmiton.org/recettes/recette_mousse-au-chocolat-facile_13585.aspx"),
("Tarte au citron", "Francais", "Dessert", "Images/Tarte au citron.jpg", "https://www.marmiton.org/recettes/recette_the-tarte-au-citron-meringuee_22082.aspx"),
("Fraisier", "Francais", "Dessert", "Images/Fraisier.jpg", "https://www.marmiton.org/recettes/recette_merveilleux-fraisier-leger_49305.aspx"),
("Tarte aux fruits", "Francais", "Dessert", "Images/Tarte aux fruits.jpg", "https://www.marmiton.org/recettes/recette_tarte-aux-fruits-d-ete_59373.aspx"),


("Cannoli siciliens", "italien", "Dessert", "Images/Cannoli siciliens.jpg", "https://www.marmiton.org/recettes/recette_cannoli-recette-sicilienne_14435.aspx"),
("Crostata ricotta aux cerises griottes", "italien", "Dessert", "Images/Crostata ricotta aux cerises griottes.jpg", "https://www.750g.com/tarte-a-la-ricotta-et-confiture-de-griottes-crostata-con-ricotta-e-visciole-r207176.htm"),
("Tiramisu original au café", "italien", "Dessert", "Images/Tiramisu original au café.png", "https://www.marmiton.org/recettes/recette_tiramisu-original_72660.aspx"),
("Castagnaccio", "italien", "Dessert", "Images/Castagnaccio.jpg", "https://www.lacuisineitalienne.fr/recette-italienne-castagnaccio/"),
("Panna cotta", "italien", "Dessert", "Images/Panna cotta.jpg", "https://www.marmiton.org/recettes/recette_panna-cotta_17991.aspx"),
("Zucotto", "italien", "Dessert", "Images/Zucotto.jpg", "https://www.750g.com/zuccotto-le-dessert-italien-r204840.htm"),
("Ciambellone", "italien", "Dessert", "Images/Ciambellone.jpg", "https://www.marmiton.org/recettes/recette_ciambellone_14579.aspx"),
("Panettone", "italien", "Dessert", "Images/Panettone.jpg", "https://www.marmiton.org/recettes/recette_panettone-recette-secrete_222534.aspx"),
("Torta della nonna", "italien", "Dessert", "Images/Torta della nonna.jpg", "https://www.lacuisineitalienne.fr/recette-italienne-torta-della-nonna/"),
("Pastiera Napolitaine", "italien", "Dessert", "Images/Pastiera Napolitaine.jpg", "https://www.lacuisineitalienne.fr/recette-italienne-pastiera-napolitaine/"),
("Torta Caprese", "italien", "Dessert", "Images/Torta Caprese.jpg", "https://www.lacuisineitalienne.fr/recette-italienne-torta-caprese/"),


("Christmas Pudding (anglais)", "Anglophone", "Dessert", "Images/Christmas Pudding.jpg", "https://www.marmiton.org/recettes/recette_christmas-pudding-traditionnel_93765.aspx"),
("Apple crumble (anglais)", "Anglophone", "Dessert", "Images/Apple crumble.jpg", "https://www.marmiton.org/recettes/recette_the-real-english-apple-crumble_48956.aspx"),
("Banoffee Pie (anglais)", "Anglophone", "Dessert", "Images/Banoffee Pie.jpg", "https://www.marmiton.org/recettes/recette_banoffy-banoffee-pie-angleterre_15346.aspx"),
("Brownie aux fruits secs (anglais)", "Anglophone", "Dessert", "Images/Brownie aux fruits secs.jpg.crdownload", "https://www.cuisineactuelle.fr/recettes/brownies-aux-fruits-secs-196478"),
("Crème anglaise safranée (anglais)", "Anglophone", "Dessert", "Images/Crème anglaise safranée.jpg", "https://www.marmiton.org/recettes/recette_creme-anglaise-reussie-onctueuse-a-souhait_37391.aspx"),
("Cake au citron (anglais)", "Anglophone", "Dessert", "Images/Cake au citron.jpg", "https://www.marmiton.org/recettes/recette_cake-au-citron_11391.aspx"),
("Carrot cake (anglais)", "Anglophone", "Dessert", "Images/Carrot cake.png", "https://www.marmiton.org/recettes/recette_carrot-cake_42455.aspx"),
("Cheese cake (anglais)", "Anglophone", "Dessert", "Images/Cheese cake.jpg", "https://www.marmiton.org/recettes/recette_cheese-cake-gateau-au-fromage-blanc-inratable_20518.aspx"),
("Crème anglaise (anglais)", "Anglophone", "Dessert", "Images/Crème anglaise.jpg", "https://www.marmiton.org/recettes/recette_creme-anglaise-reussie-onctueuse-a-souhait_37391.aspx"),
("Cupcake au citron meringué (anglais)", "Anglophone", "Dessert", "Images/Cupcake au citron meringué.jpg", "https://www.marmiton.org/recettes/recette_cupcakes-meringues-fourres-au-lemon-curd_82231.aspx"),
("Gateau victorien (anglais)", "Anglophone", "Dessert", "Images/Gateau victorien.jpg", "https://www.mesrecettesfaciles.fr/recipe/gateau-victoria"),
("Jelly aux fruits rouge (anglais)", "Anglophone", "Dessert", "Images/Jelly aux fruits rouge.jpg", "https://www.mesrecettesfaciles.fr/recipe/gelee-au-champagne-et-aux-fruits-rouges"),
("Key lime pie (anglais)", "Anglophone", "Dessert", "Images/Key lime pie.jpg", "https://www.marmiton.org/recettes/recette_key-lime-pie-le-vrai_88803.aspx"),
("Mince pies (anglais)", "Anglophone", "Dessert", "Images/Mince pies.jpg", "https://www.marmiton.org/recettes/recette_mince-pie_34127.aspx"),
("Muffins anglais (anglais)", "Anglophone", "Dessert", "Images/Muffins anglais.jpg", "https://www.marmiton.org/recettes/recette_muffins-anglais-simples_21095.aspx"),
("Scones (anglais)", "Anglophone", "Dessert", "Images/Scones.jpg", "https://www.marmiton.org/recettes/recette_scones-aux-raisins-angleterre_13912.aspx"),


("Pancakes à l'américaine", "Anglophone", "Dessert", "Images/Pancakes à l'américaine.jpg", "https://www.marmiton.org/recettes/recette_les-vrais-pancakes-a-l-americaine_17704.aspx"),
("Cheesecake new-yorkais", "Anglophone", "Dessert", "Images/Cheesecake new-yorkais.jpg", "https://www.marmiton.org/recettes/recette_recette-du-cheesecake-new-yorkais-au-citron_218635.aspx"),
("Brownies au chocolat(américain)", "Anglophone", "Dessert", "Images/Brownies au chocolat et noix.jpg", "https://www.marmiton.org/recettes/recette_veritables-brownies-aux-noix_23762.aspx"),
("Cupcakes au chocolat blanc(américain)", "Anglophone", "Dessert", "Images/Cupcakes au chocolat blanc et vanille.jpg", "https://www.cuisineaz.com/recettes/cupcakes-au-chocolat-blanc-et-vanille-79052.aspx"),
("Apple pie (américain) ", "Anglophone", "Dessert", "Images/Apple pie.jpg", "https://www.marmiton.org/recettes/recette_apple-pie-d-automne_52910.aspx"),
("Banana Bread (américain) ", "Anglophone", "Dessert", "Images/Banana Bread.jpeg", "https://www.marmiton.org/recettes/recette_cake-a-la-banane-banana-bread-usa_12042.aspx"),
("Cookies aux deux chocolats (américain) ", "Anglophone", "Dessert", "Images/Cookies aux deux chocolats.jpeg", "https://www.marmiton.org/recettes/recette_cookies-aux-deux-chocolats_18448.aspx"),
("Carrot cake (américain) ", "Anglophone", "Dessert", "Images/Carrot cake épicé au cream cheese.jpg", "https://www.cuisineaz.com/recettes/carrot-cake-epice-au-cream-cheese-79294.aspx"),
("Layer cake au café (américain) ", "Anglophone", "Dessert", "Images/Layer cake au café.jpg", "https://www.cuisineaz.com/recettes/layer-cake-au-cafe-79597.aspx"),
("Blueberry muffins (américain) ", "Anglophone", "Dessert", "Images/Blueberry muffins.jpg", "https://www.cuisineaz.com/recettes/blueberry-muffins-muffins-aux-myrtilles-70947.aspx"),
("Milkshake fraise (américain) ", "Anglophone", "Dessert", "Images/Milkshake fraise.jpg", "https://www.cuisineaz.com/recettes/milkshake-fraise-facile-65105.aspx"),
("Pecan pie (américain) ", "Anglophone", "Dessert", "Images/Pecan pie au sirop d'érable.jpg.crdownload", "https://www.cuisineaz.com/recettes/pecan-pie-au-sirop-d-erable-81553.aspx"),
("Cinnamon à la canelle (américain) ", "Anglophone", "Dessert", "Images/Cinnamon aux petits pains roulés à la canelle.jpg", "https://www.cuisineaz.com/recettes/cinnamon-rolls-ou-petits-pains-roules-a-la-cannelle-40770.aspx"),
("Whoopie pies (américain) ", "Anglophone", "Dessert", "Images/Whoopie pies au chocolat-vanille.jpg", "https://www.cuisineaz.com/recettes/whoopie-pies-chocolat-vanille-81983.aspx"),
("Red velvet cake (américain) ", "Anglophone", "Dessert", "Images/Red velvet cake.jpg", "https://www.cuisineaz.com/recettes/red-velvet-cake-67012.aspx"),
("Donut (américain) ", "Anglophone", "Dessert", "Images/Donut.jpg", "https://www.cuisineaz.com/recettes/donuts-100581.aspx"),


("Biscuits Mole New", "Mexicain", "Dessert", "Images/Biscuits de mariage mexicains Mole New.jpg", "https://juegoscocinarpasteleria.org/fr/biscuits-de-mariage-mexicain/"),
("Biscuits mexicains à la cannelle", "Mexicain", "Dessert", "Images/Biscuits mexicains à la cannelle.jpg", "https://juegoscocinarpasteleria.org/fr/hojarascas-biscuits-sables-mexicains/"),
("Churros", "Mexicain", "Dessert", "Images/Churros.jpg", "https://www.cuisineaz.com/recettes/churros-2395.aspx"),
("Sopaipillas", "Mexicain", "Dessert", "Images/Sopaipillas.jpg", "https://www.cuisineaz.com/recettes/sopapillas-beignets-mexicains-61812.aspx"),
("Biscuits au chocolat", "Mexicain", "Dessert", "Images/Biscuits au chocolat orange-chili.jpg", "https://beaus.ca/fr/recipe/biscuits-mayas-au-chocolat-et-au-chili/"),
("Croustillants au chocolat", "Mexicain", "Dessert", "Images/Croustillants au chocolat et au sucre.jpg", "https://www.750g.com/baltic-croustillant-au-chocolat-au-lait-r18335.htm"),
("Gâteau Tres Leches", "Mexicain", "Dessert", "Images/Gâteau Tres Leches.jpg", "https://www.ptitchef.com/recettes/dessert/gateau-aux-trois-laits-tres-leches-fid-1564907"),
("Flan au caramel crémeux", "Mexicain", "Dessert", "Images/Flan au caramel crémeux.jpg", "https://www.marmiton.org/recettes/recette_petits-flans-cremeux-au-caramel_308899.aspx"),
("Pâtisseries de patates douces", "Mexicain", "Dessert", "Images/Pâtisseries de patates douces à la cannelle et au sucre.jpeg", "https://recettes-du-monde.fr/frites-de-patate-douce-au-sucre-a-la-cannelle-avec-trempette-a-la-vanille/"),
("Flans au potiron", "Mexicain", "Dessert", "Images/Flans au potiron.jpg", "https://www.marmiton.org/recettes/recette_flan-de-potiron_164665.aspx"),
("Arroz Con Leche", "Mexicain", "Dessert", "Images/Arroz Con Leche.jpg", "https://www.programme-malin.com/recettes/age-1-3-ans/arroz-con-leche/"),
("Glaces frites", "Mexicain", "Dessert", "Images/Glaces frites.jpg", "https://www.marmiton.org/recettes/recette_glace-frite_346411.aspx"),
("Biscotti au chocolat maya", "Mexicain", "Dessert", "Images/Biscotti au chocolat maya.jpg", "https://guiderecettes.com/Biscuits-au-chocolat-maya-R1101448"),
("Biscochitos à la cerise", "Mexicain", "Dessert", "Images/Biscochitos à la cerise.jpg", "https://guiderecettes.com/biscochitos-(biscuits-de-mariage-mexicains)-R2705651"),
("Dulce de Leche", "Mexicain", "Dessert", "Images/Gâteau au fromage Dulce de Leche.jpg", "https://www.ptitchef.com/recettes/dessert/gateau-au-fromage-au-caramel-dulce-de-leche-fid-794918");
